export const projects: Project[] = [
    {
        id: "1",
        name: "Receita-Next-app",
        description: "App de Receitas, com next.js e docker container.",
        tech: ["Next.js", "Laravel", "PostgreSql", "Docker"],
        type: "frontend",
        status: "completed",
    //   demoUrl: "https://demo-ecommerce.example.com",
        githubUrl: "https://github.com/mcarina/Receita-Next-app",
        longDescription: `Este projeto foi desenvolvido com o objetivo de estudar e praticar o Next.js 14,
        explorando suas melhores práticas e recursos mais modernos. A estrutura foi cuidadosamente planejada 
        para ser eficiente, rápida e bem organizada, com foco em`,
        features: [
        "Autenticação de usuários",
        "CRUD completo de receitas",
        "Sistema de busca avançada",
        "Containerização com Docker",
        ],
        challenges: [
        "Implementação de cache eficiente",
        "Otimização de queries no PostgreSQL",
        "Setup de ambiente Docker multi-container",
        ],
    },
    {
        id: "2",
        name: "Boole-Bots-Pygames",
        description: "Boole-Bots-Pygames Marcy's version.",
        tech: ["React", "Redux", "Express", "PostgreSQL"],
        type: "Utilitários e Jogos",
        status: "completed",
        //   demoUrl: "https://tasks.example.com",
        githubUrl: "https://github.com/marcyexpo/task-dashboard",
    },
    {
        id: "3",
        name: "Calculadora Tkinter",
        description: "Calculadora com Tkinter 2025.",
        tech: ["Python", "TensorFlow", "Flask", "React"],
        type: "Utilitários e Jogos",
        status: "completed",
        githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
    {
        id: "4",
        name: "Receitas-Backend",
        description: "Com Laravel 11 para a aplicação Receitas-Next-App.",
        tech: ["Python", "TensorFlow", "Flask", "React"],
        type: "backend",
        status: "completed",
        githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
    {
    id: "5",
    name: "Nextjs-Docker",
    description: "iniciando Next.js com Docker container para desenvolvimento dev e produção.",
    tech: ["Python", "TensorFlow", "Flask", "React"],
    type: "DevOps",
    status: "completed",
    githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
    {
    id: "6",
    name: "Flask-Restx-Crud",
    description: "Crud com flask restx.",
    tech: ["Python", "TensorFlow", "Flask", "React"],
    type: "backend",
    status: "completed",
    githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
    {
    id: "7",
    name: "Django Rest full",
    description: "Crud com django rest framewokr.",
    tech: ["Python", "TensorFlow", "Flask", "React"],
    type: "backend",
    status: "completed",
    githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
    {
    id: "8",
    name: "Nodejs-e-express",
    description: "tudo que aprendi sobre node e express basico.",
    tech: ["Python", "TensorFlow", "Flask", "React"],
    type: "backend",
    status: "completed",
    githubUrl: "https://github.com/marcyexpo/ai-chatbot",
    },
]